# Generated by Django 3.2.18 on 2023-09-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_name', models.CharField(max_length=200)),
                ('current_day', models.CharField(max_length=20)),
                ('utc_time', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=100)),
                ('github_file_url', models.CharField(max_length=200)),
                ('github_repo_url', models.CharField(max_length=200)),
                ('status_code', models.PositiveIntegerField(default=200)),
            ],
        ),
    ]
