# Generated by Django 3.2.18 on 2023-09-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='status_code',
            new_name='status_codez',
        ),
    ]
