# Generated by Django 3.2.18 on 2023-09-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_rename_status_code_info_status_codez'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='status_codez',
            new_name='status_code',
        ),
    ]
